In [1]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5,6,7,8,9,10]
np.array(my_list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### notice how putting in a string type changes it

In [3]:
my_list = [1,2,'3',4,5,6,7,8,9,10]
np.array(my_list)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], 
      dtype='<U21')

In [5]:
my_list = [1,2,'3',4,5,[6],7,8,9,10]
np.array(my_list)

ValueError: setting an array element with a sequence

In [9]:
my_list = [1,2,3,4,5,6,7,8,9,10]
this_array = np.array(my_list)
sliced_array = np.array(my_list)[:5]
print(sliced_array)

[1 2 3 4 5]


In [10]:
this_array ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
this_array # no mutation

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
this_array[1] = np.pi
this_array

array([ 1,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
this_array.dtype

dtype('int64')

In [20]:
this_array.astype(str)

array(['1', '3', '3', '4', '5', '6', '7', '8', '9', '10'], 
      dtype='<U21')

In [21]:
this_array # no mutation

array([ 1,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
that_array = np.arange(11, 20)

In [27]:
new_array = np.concatenate((this_array, that_array)) # double parens

In [26]:
new_array

array([ 1,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
len(new_array)

19

In [30]:
np.linspace(0, 20, 11) # linear spacing

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.])

In [32]:
np.logspace(0, 3, 5)  # log spacing

array([    1.        ,     5.62341325,    31.6227766 ,   177.827941  ,
        1000.        ])

In [33]:
this_array[this_array < 4]

array([1, 3, 3])

In [34]:
this_array < 4

array([ True,  True,  True, False, False, False, False, False, False, False], dtype=bool)

In [36]:
np.where((this_array < 4) & (this_array > 0)) # index, val --> output index

(array([0, 1, 2]),)

In [37]:
this_array

array([ 1,  3,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4, 2, 1, 5])
arr1 * arr2

array([ 4,  4,  3, 20])

In [42]:
arr3 = arr1.cumsum() # cumulative sum
arr3

array([ 1,  3,  6, 10])